name: Feature Proposal
description: Propose a feature with details
title: '[Feature]: replace_with_a_clear_understandable_name'
labels: ['feature', 'proposal']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature proposal!
  - type: input
    id: contact
    attributes:
      label: Contact Details (Optional)
      description: Is there a customer get in touch for this feature?
      placeholder: ex. email@example.com, twitter handle, etc.
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What's the current behavior?
      description: Or what's the problem statement? Why do you think it's necessary to implement this feature?
      placeholder: What do you see?
      value: |
        "Description:
        Screenshots:
        Terminal outputs:
        What are the steps to reproduce the current behavior?
        "
    validations:
      required: true
  - type: textarea
    id: what-expected
    attributes:
      label: What's the expected behavior?
      description: What do you want to achieve with this feature? What's the goal?
      value: |
        "What do you want to achieve with this feature? What's the goal?
        "
    validations:
      required: true
  - type: textarea
    id: further-research
    attributes:
      label: Further research
      description: What other further research did you do? Whats the implementation from others? Be as detailed as possible with code snippet or example terminal output.
  - type: textarea
    id: feature-usage
    attributes:
      label: Feature usage
      description: How will developers and customers use this feature? How will engineer and customers interact, use this feature once it is completed?
      placeholder: ex. email@example.com
      value: |
        "On user end: Every terminal return, if it is failed, it should attached with a trace ID where they can send it back to us to inspect the stack trace.
        On developer end: We should be able to use the Trace ID to see the full stack trace and understand which part of the system is causing failure."
    validations:
      required: true
  - type: textarea
    id: product-to-use
    attributes:
      label: Related external product
      description: Is there any related external product for this feature How will we use it?
      placeholder: ex. email@example.com
      value: |
        "Option 1: acme.com
        Each one of us will need an account to log into acme.com to inspect trace ID.
        Optionally we can also query the logging result and use it else where."
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional information (Optional)
      description: Is there any additional information or reference the team should know?
      placeholder: 'Example: TheMonitoringCompany is also a good product to use.'
      value: |
        " We will need environment secrets injected in Github Action. When the CI runs to bundle the application, it will inject secrets into the build Output. This is not optimal and it's a temporary solution for now until we have a custom logging endpoint without needing a secret."
    validations:
      required: false